# Generated by Django 2.1.5 on 2020-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Soul'), ('C', 'Chinese'), ('I', 'Italian'), ('F', 'Fast Food'), ('IN', 'Indian')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
